Separate model from particle filter
Team-RADDISH/ParticleDA.jl pull request #128
Opened 2020-09-28 15:19 UTC by giordano

Still a work in progress, but not too far from the goal of #124.

Things that are still entangled:

* input parameters: instead of creating complicated custom data types for the parameters of the particle filter _and_ of the model, we may have a single dictionary-like data type.  It isn't super fancy, but should do the job good enough and could be flexible enough for multiple different model.

* writing to the output HDF5 is strongly coupled between filter and model.  I'm thinking about having the model to define a function `write_snapshot(::ModelData)`, and maybe also `write_initial_state(::ModelData)`, but as it is now the I/O functions write at the same time all data, in a somewhat correlated way.  We need to better figure out how to efficiently do this, especially to avoid opening/closing the HDF5 multiple times.

2020-09-28 15:26 UTC, giordano commented on src/ParticleDA.jl
> -    sqrt((float(i0 - i1) * dx) ^ 2 + (float(j0 - j1) * dy) ^ 2)
This function doesn't seem to be used anywhere, apart from the tests

2020-09-28 15:26 UTC, giordano commented on src/ParticleDA.jl
> +    var_arr = Array{T,3}(undef, nx, ny, n_state_var)
I think the sizes of these arrays should come from the model.  It needs to somehow pass the size `(nx, ny, n_state_var)` to the filter.

2020-09-28 15:26 UTC, giordano commented on src/ParticleDA.jl
> +        # @timeit_debug timer "IO" write_initial_state(model_data, params)
I/O temporarily disabled, until we figure out how to do this properly

2020-09-28 15:26 UTC, giordano commented on src/ParticleDA.jl
> +                # write_snapshot(states.truth, avg_arr, var_arr, weights, it, params)
I/O temporarily disabled, until we figure out how to do this properly

2020-09-28 15:26 UTC, giordano commented on src/ParticleDA.jl
> +                # write_timers(length_timer, my_size, timer_chars, params)
I/O temporarily disabled, until we figure out how to do this properly

2020-09-28 15:26 UTC, giordano commented on src/ParticleDA.jl
> +function run_particle_filter(path_to_input_file::String = "")
Also this function should get the `init` function as argument

2020-09-28 15:26 UTC, giordano commented on src/ParticleDA.jl
> +function run_particle_filter(params::Parameters)
Also this function should get the `init` function as argument

2020-09-28 15:26 UTC, giordano commented on src/model.jl
> +end
Once we finalise the data types, this needs to be concretely annotated, maybe using parameters, for better performance

2020-09-28 15:26 UTC, giordano commented on test/runtests.jl
> -    @test ParticleDA.get_distance(10, 23, 5, 11, dx, dy) == 26000.0
As above, this function doesn't seem to be used anywhere

2020-09-29 15:28 UTC, giordano commented on src/model.jl
> +end
Done.  Much to my surprise, this doesn't give a large performance improvement.

2020-09-29 17:21 UTC, giordano commented on src/ParticleDA.jl
> -end
This method isn't needed anymore, we're calling directly the one below.

2020-09-30 22:06 UTC, giordano commented on src/ParticleDA.jl
> -function tdac(path_to_input_file::String, rng::AbstractRNG)
The diff is screwing things up a bit, what I did here was to remove this method and keep only the two other methods below

2020-10-23 13:06 UTC, tkoskela reviewed
Overall I think this looks pretty good! I added a few comments.

2020-10-26 16:49 UTC, giordano commented on test/model/model.jl
> +# value of `particle_filter`, we may just return the whole `model_data`.
Yes, no problem having the same signature for `update_truth!` and `update_particles!`, it makes a lot of sense.

I'm going to pass `nprt_per_rank` also to `update_truth!`, it'd simply be ignored in the implementation of the model in the tests.  If the user wants to pass a single model they can do:
```julia
function ParticleDA.update_particles!(data::ModelData, nprt_per_rank)
    # ...
end

function ParticleDA.update_truth!(data::ModelData, nprt_per_rank)
    ParticleDA.update_particles!(data::ModelData, nprt_per_rank)
end
```

2020-10-26 17:19 UTC, giordano commented on test/model/model.jl
> +include("llw2d.jl")
Done: now the file `llw2d.jl` is completely unchanged, the file `model.jl` defines the `Model` module.

2020-10-26 17:29 UTC, giordano commented on src/ParticleDA.jl
> +                           particles::AbstractArray{T,4},
BTW, this is basically the same comment as https://github.com/Team-RADDISH/ParticleDA.jl/pull/128#discussion_r496034922 :sweat_smile:  Maybe the size could be passed as a tuple by the `init` function?

2020-10-28 14:34 UTC, tkoskela requested changes
Can you please update the usage section in README.md?

2020-11-05 18:54 UTC, giordano commented
I've reduced the README to the very minimum, when this PR will be merged, the documentation will be published to a website based on GitHub Pages.

2020-11-10 09:52 UTC, tkoskela approved these changes

2020-11-10 09:53 UTC, merged